[package]
name = "village-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.3"
mongodb = "3.0.0"
shuttle-axum = "0.49.0"
shuttle-runtime = "0.49.0"
user-module = { path = "../user", features = ["axum_router"] }
auth-module = { path = "../auth", features = [] }
base64 = "0.22.1"